server:
  port: 8081
  servlet:
    context-path: /user
user:
  nickName: 谭富文
  age: 18
  info: ${user.nickName}今年${user.age}

spring:
  profiles:
    active: pro
  datasource:
    url: jdbc:mysql://localhost:3306/db1
    username: root
    password: 952714
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties: hibernate.hbm2ddl.auto=update
      hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
